// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxtyetybfjqabxwvzsrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4dHlldHliZmpxYWJ4d3Z6c3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzIxMDQsImV4cCI6MjA2NDI0ODEwNH0.jpTqh5eOCXFgc3F7vZaX97OhdOtC66jx6GtWbr1rtG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);